Repository ZZinBros/miniprojects-2019, pull requests merged in 2019-08, with the labels that each got.

#94 LoginSessionManager 추가 및 UserService에 로그인 유저 조회 기능 구현
  src/main/java/com/woowacourse/zzinbros/post/web/PostController.java
  src/main/java/com/woowacourse/zzinbros/post/web/PostEditController.java
  src/main/java/com/woowacourse/zzinbros/user/dto/LoginUserDto.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/main/java/com/woowacourse/zzinbros/user/web/LogoutController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/LoginController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/LogoutController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/UserController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/UserEditPageController.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/LoginSessionManager.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/SessionInfo.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserArgumentResolver.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserSession.java
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/LoginControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/LogoutControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/UserControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/UserEditPageControllerTest.java
Labels: back, improve, shortterm

#99 .gitignore에서 gradle-wrapper.jar 제외
  .gitignore
Labels: back, shortterm

#100 feat(yml): application.yml 파일의 profile을 local, deploy, test로 분리
  src/main/resources/application.yml
  src/test/java/com/woowacourse/zzinbros/BaseTest.java
  src/test/java/com/woowacourse/zzinbros/ZzinbrosApplicationTests.java
  src/test/java/com/woowacourse/zzinbros/post/domain/PostTest.java
  src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
  src/test/java/com/woowacourse/zzinbros/resources/application.yml
  src/test/java/com/woowacourse/zzinbros/user/domain/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/LoginControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/LogoutControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/UserControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/UserEditPageControllerTest.java
Labels: back

#101 유저별 페이지 구현
  .gitignore
  src/main/java/com/woowacourse/zzinbros/post/domain/repository/PostRepository.java
  src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
  src/main/resources/static/js/user-page-add.js
  src/main/resources/templates/element/cards.html
  src/main/resources/templates/element/right-sidebar-detail.html
  src/main/resources/templates/layout/center-container.html
  src/main/resources/templates/layout/right-sidebar.html
  src/main/resources/templates/user-page.html
  src/test/java/com/woowacourse/zzinbros/post/domain/repository/PostRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
  src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/LoginControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/LogoutControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/UserControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/UserEditPageControllerTest.java
Labels: back, shortterm

#107 Hotfix : 실패 테스트를 통과시켰습니다.
  src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
Labels: urgent

#109 유저 페이지 메인 화면 추가
  src/main/resources/static/css/user-page.css
  src/main/resources/templates/common/header.html
  src/main/resources/templates/element/user-info-card.html
  src/main/resources/templates/layout/user-page-cover.html
  src/main/resources/templates/layout/user-page-info.html
  src/main/resources/templates/layout/user-page-tabs.html
  src/main/resources/templates/user-page.html
Labels: front

#104 친구 기능 백엔드 구현
  src/main/java/com/woowacourse/zzinbros/user/domain/User.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/UserRepository.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
Labels: back, challenge, shortterm

#112 setting(yml): databse-platform 설정 Mysql5Dialet -> MySQL5InnoDBDialect
  src/main/java/com/woowacourse/zzinbros/user/domain/User.java
  src/main/resources/application.yml
Labels: back, urgent

#113 Hotfix : 이메일 중복 검사 수정
  src/main/java/com/woowacourse/zzinbros/user/exception/EmailAlreadyExistsException.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
Labels: urgent

#115 PostPageController에서 user-page class path 수정
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
Labels: urgent

#117 feat(friend) : 친구 등록을 프론트 페이지와 연동
  src/main/java/com/woowacourse/zzinbros/post/web/PostController.java
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
  src/main/java/com/woowacourse/zzinbros/user/domain/User.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/UserRepository.java
  src/main/java/com/woowacourse/zzinbros/user/dto/FriendDto.java
  src/main/java/com/woowacourse/zzinbros/user/dto/UserResponseDto.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/FriendController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/LoginController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/UserController.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/LoginSessionManager.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserArgumentResolver.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserSession.java
  src/main/resources/static/css/user-page.css
  src/main/resources/static/js/friend-add.js
  src/main/resources/templates/element/friend-card.html
  src/main/resources/templates/element/user-info-card.html
  src/main/resources/templates/element/user-page-cover.html
  src/main/resources/templates/element/user-tab-contents.html
  src/main/resources/templates/layout/user-page-cover.html
  src/main/resources/templates/layout/user-page-tabs.html
  src/main/resources/templates/user-page.html
  src/test/java/com/woowacourse/zzinbros/user/domain/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/FriendControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/LoginControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/LogoutControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/UserControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/UserEditPageControllerTest.java
Labels: back, challenge, front, new feature

#121 feat(mediafile): 이미지 업로드 기능 추가
  src/main/java/com/woowacourse/zzinbros/common/AppConfig.java
  src/main/java/com/woowacourse/zzinbros/mediafile/MediaFile.java
  src/main/java/com/woowacourse/zzinbros/mediafile/MediaFileRepository.java
  src/main/java/com/woowacourse/zzinbros/mediafile/web/support/UploadFileResolver.java
  src/main/java/com/woowacourse/zzinbros/mediafile/web/support/UploadTo.java
  src/main/java/com/woowacourse/zzinbros/mediafile/web/support/UploadToLocal.java
  src/main/java/com/woowacourse/zzinbros/mediafile/web/support/UploadToS3.java
  src/main/java/com/woowacourse/zzinbros/mediafile/web/support/UploadedFile.java
  src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
  src/main/java/com/woowacourse/zzinbros/post/service/PostWithImageService.java
  src/main/java/com/woowacourse/zzinbros/post/web/PostController.java
  src/main/java/com/woowacourse/zzinbros/post/web/PostWithImageController.java
  src/main/resources/static/js/social-feed.js
  src/main/resources/templates/element/card-contents.html
  src/main/resources/templates/layout/add-post-with-image-modal.html
  src/main/resources/templates/layout/social-feed.html
  src/test/java/com/woowacourse/zzinbros/learningtest/TestForLearn.java
  src/test/java/com/woowacourse/zzinbros/mediafile/web/support/AuthedWebTestClient.java
  src/test/java/com/woowacourse/zzinbros/mediafile/web/support/UploadFileResolverTest.java
  src/test/java/com/woowacourse/zzinbros/mediafile/web/support/UploadFileTest.java
  src/test/java/com/woowacourse/zzinbros/post/web/PostWithImageControllerTest.java
Labels: back, front, new feature

#126 fix(test): 학습테스트 제거
  src/test/java/com/woowacourse/zzinbros/learningtest/TestForLearn.java
Labels: urgent

#134 refactor(Comment): 아침의 팀내 피드백 반영
  src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
  src/main/java/com/woowacourse/zzinbros/comment/domain/Comment.java
  src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
  src/test/java/com/woowacourse/zzinbros/comment/controller/CommentControllerTest.java
  src/test/java/com/woowacourse/zzinbros/comment/domain/CommentTest.java
  src/test/java/com/woowacourse/zzinbros/comment/service/CommentServiceTest.java
Labels: back, feedback, improve, refactoring, shortterm

#147 chore(Log settings): 로그 관련 설정 적용
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-access.xml
  src/main/resources/logback.xml
Labels: agreement, refactoring, shortterm

#149 fix(logback-access.xml): 의도하지 않은 줄바꿈 삽입 제거
  src/main/resources/logback-access.xml
Labels: shortterm

#145 Entrance page 추가
  src/main/java/com/woowacourse/zzinbros/demo/DemoController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/LoginController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/UserController.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserControllerExceptionAdvice.java
  src/main/resources/static/css/index.css
  src/main/resources/templates/element/headline-user.html
  src/main/resources/templates/element/userpage/friend-card.html
  src/main/resources/templates/element/userpage/user-info-card.html
  src/main/resources/templates/element/userpage/user-page-cover.html
  src/main/resources/templates/element/userpage/user-tab-contents.html
  src/main/resources/templates/entrance.html
  src/main/resources/templates/layout/entrance/headline.html
  src/main/resources/templates/layout/entrance/left-logo.html
  src/main/resources/templates/layout/entrance/login-area.html
  src/main/resources/templates/layout/entrance/signup-area.html
  src/main/resources/templates/layout/headline.html
  src/main/resources/templates/layout/social-feed.html
  src/main/resources/templates/layout/userpage/user-page-info.html
  src/main/resources/templates/layout/userpage/user-page-tabs.html
  src/main/resources/templates/user-page.html
  src/test/java/com/woowacourse/zzinbros/user/web/controller/LoginControllerTest.java
Labels: front, new feature, shortterm

#150 domain 중복 제거를 위한 BaseEntity 추가
  src/main/java/com/woowacourse/zzinbros/comment/domain/Comment.java
  src/main/java/com/woowacourse/zzinbros/common/domain/BaseEntity.java
  src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
  src/main/java/com/woowacourse/zzinbros/user/domain/User.java
Labels: back, refactoring, shortterm

#155 기본 image 파일 추가
  .gitignore
  src/main/resources/static/images/default/eastjun_big.jpg
  src/main/resources/static/images/default/eastjun_profile.jpg
  src/main/resources/static/images/default/icons.png
  src/main/resources/static/images/default/icons2.png
  src/main/resources/static/images/default/plus_btn.png
  src/main/resources/static/images/default/profile-default.png
  src/main/resources/static/images/logo/favicon.ico
  src/main/resources/static/images/logo/friend_logo.png
  src/main/resources/static/images/logo/logo_thumnail_bg.jpg
  src/main/resources/static/images/logo/wootecobook.png
Labels: urgent

#169 [BACK] Friend Service, Controller 클래스 리팩토링
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
  src/main/java/com/woowacourse/zzinbros/user/domain/Friend.java
  src/main/java/com/woowacourse/zzinbros/user/domain/FriendMatcher.java
  src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/FriendController.java
  src/test/java/com/woowacourse/zzinbros/common/domain/TestBaseMock.java
  src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserBaseTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserAndFriendRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserBaseTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/FriendControllerTest.java
Labels: back, improve

#172 fix(application.yml, PostPageController)
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
Labels: back, shortterm, urgent

#179 refactor : Logout Post 방식으로 개선
  src/main/java/com/woowacourse/zzinbros/user/web/controller/LogoutController.java
  src/main/resources/static/js/logout.js
  src/main/resources/templates/common/cdns.html
  src/main/resources/templates/element/headline-user.html
Labels: urgent

#181 Friend와 User 양방향 맵핑
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
  src/main/java/com/woowacourse/zzinbros/user/domain/Friend.java
  src/main/java/com/woowacourse/zzinbros/user/domain/FriendMatcher.java
  src/main/java/com/woowacourse/zzinbros/user/domain/User.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepository.java
  src/main/java/com/woowacourse/zzinbros/user/dto/UserResponseDto.java
  src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/FriendController.java
  src/main/resources/static/css/user-page.css
  src/main/resources/templates/element/userpage/user-page-cover.html
  src/test/java/com/woowacourse/zzinbros/post/web/PostPageControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserBaseTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/UserTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserAndFriendRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/FriendControllerTest.java
Labels: back

#177 refactor(Comment): 오류 처리 및 테스트 개선
  .gitignore
  src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
  src/main/java/com/woowacourse/zzinbros/comment/controller/CommentControllerExceptionAdvice.java
  src/main/java/com/woowacourse/zzinbros/comment/dto/CommentResponseDto.java
  src/main/java/com/woowacourse/zzinbros/comment/exception/CommentNotFoundException.java
  src/main/java/com/woowacourse/zzinbros/comment/exception/UnauthorizedException.java
  src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserSession.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/static/css/app.css
  src/main/resources/static/js/comment.js
  src/main/resources/templates/element/card-action-detail.html
  src/main/resources/templates/element/cards.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user-page.html
  src/test/java/com/woowacourse/zzinbros/comment/controller/CommentControllerTest.java
  src/test/java/com/woowacourse/zzinbros/comment/domain/CommentTest.java
  src/test/java/com/woowacourse/zzinbros/comment/service/CommentServiceTest.java
Labels: back, improve, pair, refactoring, shortterm

#184 index페이지에 user-list 출력 기능
  src/main/java/com/woowacourse/zzinbros/demo/DemoController.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/main/resources/templates/element/right-sidebar-detail.html
Labels: back, front, improve

#186 feat(Comment): 프론트엔드에서 댓글 달기, 수정, 삭제 구현
  src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
  src/main/java/com/woowacourse/zzinbros/comment/controller/CommentControllerExceptionAdvice.java
  src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
  src/main/resources/static/js/comment.js
  src/main/resources/templates/element/card-action-detail.html
  src/main/resources/templates/element/cards.html
  src/test/java/com/woowacourse/zzinbros/comment/controller/CommentControllerTest.java
  src/test/java/com/woowacourse/zzinbros/comment/service/CommentServiceTest.java
Labels: back, front, new feature, pair

#197 feat(logback-access): 배포 서버의 HTTP 로그를 단순하게 바꿈
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/logback-access-full.xml
  src/main/resources/logback-access-simple.xml
Labels: back, refactoring, shortterm

#198 feat(commnet): index 페이지 comment 초기화
  src/main/java/com/woowacourse/zzinbros/comment/controller/CommentController.java
  src/main/resources/static/js/comment.js
Labels: front, new feature

#200 entrance, index 페이지 제어 방식 변경
  src/main/java/com/woowacourse/zzinbros/demo/DemoController.java
  src/test/java/com/woowacourse/zzinbros/demo/DemoControllerTest.java
Labels: back, improve

#203 feat(Comment): 댓글 단 시간을 상대 시간으로 보여주는 기능 추가
  src/main/resources/static/js/comment.js
  src/main/resources/static/js/time-update.js
  src/main/resources/templates/common/cdns.html
  src/main/resources/templates/index.html
Labels: front, improve, new feature, shortterm

#205 친구 요청 거절 기능
  src/main/java/com/woowacourse/zzinbros/post/web/PostPageController.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepository.java
  src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/FriendController.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/rest/FriendRequestController.java
  src/main/resources/application-test.yml
  src/main/resources/data.sql
  src/main/resources/static/css/app.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/friend-add.js
  src/main/resources/static/js/friend-delete.js
  src/main/resources/static/js/friend-list.js
  src/main/resources/static/js/logout.js
  src/main/resources/templates/common/cdns.html
  src/main/resources/templates/element/userpage/user-page-cover.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/friend-list-btn.html
  src/main/resources/templates/layout/friend-request-btn.html
  src/main/resources/templates/layout/headline.html
  src/main/resources/templates/mypage-edit.html
  src/main/resources/templates/user-page.html
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/AcceptanceFriendControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/rest/FriendRequestControllerTest.java
Labels: back, front, shortterm

#206 feat(Post): 글을 쓴 시간을 상대적으로 보여주는 기능 추가
  src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
  src/main/resources/static/js/comment.js
  src/main/resources/static/js/time-update.js
  src/main/resources/templates/common/cdns.html
  src/main/resources/templates/element/card-header.html
  src/main/resources/templates/index.html
Labels: front, improve, new feature, shortterm

#212 [3주차] 배포시 test 깨지는 버그 수정
  src/main/java/com/woowacourse/zzinbros/user/web/controller/UserController.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserControllerExceptionAdvice.java
  src/main/resources/static/js/social-feed.js
  src/main/resources/templates/layout/entrance/signup-area.html
  src/test/java/com/woowacourse/zzinbros/common/domain/AuthedWebTestClient.java
  src/test/java/com/woowacourse/zzinbros/demo/DemoControllerTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/AcceptanceUserControllerTest.java
Labels: back, refactoring, urgent

#213 refactor(login): front에서 로그인 오류 메시지 띄워주도록 수정
  src/main/java/com/woowacourse/zzinbros/user/web/controller/LoginController.java
  src/main/java/com/woowacourse/zzinbros/user/web/support/UserControllerExceptionAdvice.java
  src/main/resources/templates/element/card-header.html
  src/main/resources/templates/layout/entrance/headline.html
  src/main/resources/templates/user-page.html
  src/test/java/com/woowacourse/zzinbros/user/web/controller/AcceptanceLoginControllerTest.java
Labels: front, refactoring, urgent

#214 유저 수정 페이지에서 예외에 따른 메시지 출력
  src/main/java/com/woowacourse/zzinbros/user/domain/User.java
  src/main/java/com/woowacourse/zzinbros/user/dto/ModifyResponseMessage.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/UserController.java
  src/main/resources/static/js/messager.js
  src/main/resources/static/js/user-delete.js
  src/main/resources/static/js/user-edit.js
  src/main/resources/templates/layout/user-edit-area.html
  src/main/resources/templates/mypage-edit.html
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/AcceptanceUserControllerTest.java
Labels: back, front, improve, shortterm
