Repository ZZinBros/miniprojects-2019, pull requests merged in 2019-09, with the labels that each got.

#232 entrance 페이지 logo max-width 설정
  src/main/resources/static/css/entrance.css
  src/main/resources/templates/entrance.html
  src/main/resources/templates/layout/entrance/headline.html
  src/main/resources/templates/layout/entrance/left-logo.html
  src/main/resources/templates/layout/entrance/login-area.html
Labels: front, refactoring

#233 feat(comment): 다른 유저의 댓글 수정 시도시 front에서도 block
  src/main/resources/static/js/comment.js
Labels: front, refactoring

#234 refactor(Time): 상대 시간 기능 개선
  src/main/java/com/woowacourse/zzinbros/demo/DemoController.java
  src/main/resources/static/js/time-update.js
  src/main/resources/templates/common/cdns.html
  src/test/java/com/woowacourse/zzinbros/demo/DemoControllerTest.java
Labels: back, front, improve, refactoring

#238 이름으로 유저 검색 기능 추가
  src/main/java/com/woowacourse/zzinbros/common/web/controller/MainController.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepository.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/UserRepository.java
  src/main/java/com/woowacourse/zzinbros/user/service/SearchService.java
  src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
  src/main/java/com/woowacourse/zzinbros/user/web/controller/rest/SearchController.java
  src/main/resources/static/js/search-name.js
  src/main/resources/templates/element/right-sidebar-detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/left-profile.html
  src/main/resources/templates/layout/search-bar.html
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/SearchServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/UserServiceTest.java
  src/test/java/com/woowacourse/zzinbros/user/web/controller/AcceptanceSearchControllerTest.java
  test.png
Labels: challenge

#244 refactor(OffsetDateTime): LocalDateTime을 OffsetDateTime으로 교체
  src/main/java/com/woowacourse/zzinbros/comment/dto/CommentResponseDto.java
  src/main/java/com/woowacourse/zzinbros/comment/web/controller/rest/CommentController.java
  src/main/java/com/woowacourse/zzinbros/common/domain/BaseEntity.java
  src/main/java/com/woowacourse/zzinbros/common/web/controller/rest/DateTimeController.java
  src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
  src/test/java/com/woowacourse/zzinbros/common/domain/TestBaseMock.java
  src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
Labels: back, improve, refactoring, shortterm

#247 friend-list.js 백틱 리터럴 써서 수정
  src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
  src/main/resources/static/js/friend-list.js
  src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
Labels: front, improve

#250 FriendService 클래스 리팩토링
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepository.java
  src/main/java/com/woowacourse/zzinbros/user/domain/repository/FriendRequestRepository.java
  src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/FriendRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/FriendRequestRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/domain/repository/UserAndFriendRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/user/service/FriendServiceTest.java
Labels: back, refactoring

#251 fix(Comment): 댓글에 HTML이나 자바스크립트가 적용되는 문제점 해결
  build.gradle
  src/main/java/com/woowacourse/zzinbros/comment/dto/CommentResponseDto.java
  src/main/java/com/woowacourse/zzinbros/common/EscapedCharacters.java
Labels: feedback

#239 feat(notification): backend에 새로운 게시물 알림 기능 추가
  src/main/java/com/woowacourse/zzinbros/notification/domain/NotificationType.java
  src/main/java/com/woowacourse/zzinbros/notification/domain/PostNotification.java
  src/main/java/com/woowacourse/zzinbros/notification/domain/repository/NotificationRepository.java
  src/main/java/com/woowacourse/zzinbros/notification/dto/NotificationResponseDto.java
  src/main/java/com/woowacourse/zzinbros/notification/exception/NotifyFailException.java
  src/main/java/com/woowacourse/zzinbros/notification/service/NotificationService.java
  src/main/java/com/woowacourse/zzinbros/notification/web/NotificationController.java
  src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
  src/main/resources/data.sql
  src/main/resources/static/js/comment.js
  src/main/resources/templates/element/card-contents.html
  src/test/java/com/woowacourse/zzinbros/notification/domain/PostNotificationTest.java
  src/test/java/com/woowacourse/zzinbros/notification/domain/repository/NotificationRepositoryTest.java
  src/test/java/com/woowacourse/zzinbros/notification/service/NotificationServiceTest.java
  src/test/java/com/woowacourse/zzinbros/notification/web/NotificationControllerTest.java
  src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
Labels: back, challenge, new feature
